services:
  redis:
    image: redis/redis-stack-server:latest
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    command: redis-server --save 20 1 --loglevel warning 
      --requirepass redisDockerTestPassword 
      --loadmodule /opt/redis-stack/lib/redisearch.so
      --loadmodule /opt/redis-stack/lib/rejson.so


volumes:
  redis-volume:
    driver: local