services:
  redis:
    image: redis:7.2-alpine
    container_name: redis
    restart: on-failure
    ports:
      - "6379:6379"
    volumes:
      - redis-volume:/data
    command: redis-server --save 20 1 --loglevel warning --requirepass redisDockerTestPassword

  stockcomp-client-backend:
    container_name: fastfinance
    build:
      context: .
    depends_on:
      - redis
    restart: on-failure
    ports:
      - "8000:8000"
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
      REDIS_USER: default
      REDIS_PASSWORD: redisDockerTestPassword

volumes:
  redis-volume:
    driver: local